project_id = "ibfcgweykqkzdodrfmci"

[functions.affiliate-registration]
verify_jwt = false

[functions.customer-management]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.journal-publication-form]
verify_jwt = false

[functions.platform-auth]
verify_jwt = false

[functions.platform-migration]
verify_jwt = false

[functions.platform-orders]
verify_jwt = false

[functions.platform-services]
verify_jwt = false

[functions.platform-users]
verify_jwt = false

[functions.reset-password-confirm]
verify_jwt = false

[functions.send-academic-expertise-inquiry]
verify_jwt = false

[functions.send-document-translation-inquiry]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-job-application]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.send-order-status-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-pricing-inquiry]
verify_jwt = false

[functions.send-service-inquiry]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false